[versions]
# https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies
spring-cloud = "2025.1.1"
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot
spring-boot = "4.0.2"
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin
kotlin = "2.2.21"
# https://plugins.gradle.org/plugin/org.barfuin.gradle.jacocolog
jacoco = "4.0.1"
# https://mvnrepository.com/artifact/com.diffplug.spotless/spotless-plugin-gradle
spotless = "8.2.1"
# https://mvnrepository.com/artifact/io.kotest/kotest-runner-junit5-jvm
kotest = "6.1.2"
# https://mvnrepository.com/artifact/io.kotest.extensions/kotest-extensions-spring
kotest-spring = "1.3.0"
# https://mvnrepository.com/artifact/io.kotest/kotest-extensions-now-jvm
kotest-now = "6.1.2"
# https://mvnrepository.com/artifact/org.assertj/assertj-core
assertj = "3.27.7"
# https://mvnrepository.com/artifact/com.ninja-squad/springmockk
spring-mockk = "5.0.1"
# https://mvnrepository.com/artifact/net.logstash.logback/logstash-logback-encoder
logback-encoder = "9.0"
# https://mvnrepository.com/artifact/com.datadoghq/dd-trace-api
datadog = "1.58.2"
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core
kotlinx = "1.10.2"
# https://mvnrepository.com/artifact/org.wiremock/wiremock-standalone
wiremock = "3.13.2"
# https://mvnrepository.com/artifact/org.testcontainers/testcontainers
testcontainers = "2.0.3"
# https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui
spring-docs = "3.0.1"
# https://mvnrepository.com/artifact/io.github.springwolf/springwolf-core
springwolf = "2.0.0"
# https://mvnrepository.com/artifact/org.graalvm.buildtools/native-maven-plugin
native-build-tools = "0.11.4"

# https://github.com/google/ksp/releases
ksp = "2.3.5"

java = "21"

[libraries]
# spring
spring-boot-cloud-dependencies = { version.ref = "spring-cloud", module = "org.springframework.cloud:spring-cloud-dependencies" }
spring-boot-dependencies = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-dependencies" }
spring-boot-starter-actuator = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jpa = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-aspectj = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter-aspectj" }
spring-boot-starter-web = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webflux = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-jetty = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter-jetty" }
spring-boot-starter-logging = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter-logging" }
spring-boot-configuration-processor = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-test = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-starter" }
spring-boot-testcontainers = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-testcontainers" }
spring-boot-autoconfigure = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-kafka = { version.ref = "spring-boot", module = "org.springframework.kafka:spring-kafka" }
spring-kafka-test = { version.ref = "spring-boot", module = "org.springframework.kafka:spring-kafka-test" }
spring-tx = { version.ref = "spring-boot", module = "org.springframework:spring-tx" }
spring-cloud-starter-openfeign = { version.ref = "spring-cloud", module = "org.springframework.cloud:spring-cloud-starter-openfeign" }

# spring extras
springdoc-openapi-starter-webmvc-ui = { version.ref = "spring-docs", module = "org.springdoc:springdoc-openapi-starter-webmvc-ui" }
springwolf-kafka = { version.ref = "springwolf", module = "io.github.springwolf:springwolf-kafka" }
springwolf-ui = { version.ref = "springwolf", module = "io.github.springwolf:springwolf-ui" }
springmockk = { version.ref = "spring-mockk", module = "com.ninja-squad:springmockk" }

# java
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api" }

# flyway
flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }

# testcontainers
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-jdbc = { module = "org.testcontainers:jdbc", version.ref = "testcontainers" }

# postgresql
postgresql-connector = { module = "org.postgresql:postgresql" }

# kotlin
kotlinx-coroutines-core = { version.ref = "kotlinx", module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-reactor = { version.ref = "kotlinx", module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinx-coroutines-reactive = { version.ref = "kotlinx", module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive" }

# logback
logback-encoder = { version.ref = "logback-encoder", module = "net.logstash.logback:logstash-logback-encoder" }

# datadog
dd-trace-api = { version.ref = "datadog", module = "com.datadoghq:dd-trace-api" }

# testing
kotest-runner-junit5-jvm = { version.ref = "kotest", module = "io.kotest:kotest-runner-junit5-jvm" }
kotest-assertions-core-jvm = { version.ref = "kotest", module = "io.kotest:kotest-assertions-core-jvm" }
kotest-property-jvm = { version.ref = "kotest", module = "io.kotest:kotest-property-jvm" }
kotest-extensions-spring = { version.ref = "kotest-spring", module = "io.kotest.extensions:kotest-extensions-spring" }
kotest-extensions-now = { version.ref = "kotest-now", module = "io.kotest:kotest-extensions-now" }
assertj-core = { version.ref = "assertj", module = "org.assertj:assertj-core" }
wiremock-standalone = { version.ref = "wiremock", module = "org.wiremock:wiremock-standalone" }

# jackson
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }


[plugins]

kotlin = { version.ref = "kotlin", id = "org.jetbrains.kotlin.jvm" }
kotlin-spring = { version.ref = "kotlin", id = "org.jetbrains.kotlin.plugin.spring" }
kotlin-all-open = { version.ref = "kotlin", id = "org.jetbrains.kotlin.plugin.allopen" }
kotlin-no-arg = { version.ref = "kotlin", id = "org.jetbrains.kotlin.plugin.noarg" }
kotlin-jpa = { version.ref = "kotlin", id = "org.jetbrains.kotlin.plugin.jpa" }
spring-boot = { version.ref = "spring-boot", id = "org.springframework.boot" }
jacoco = { version.ref = "jacoco", id = "org.barfuin.gradle.jacocolog" }
spotless = { version.ref = "spotless", id = "com.diffplug.spotless" }
native-build-tools = { version.ref = "native-build-tools", id = "org.graalvm.buildtools.native" }
ksp = { version.ref = "ksp", id = "com.google.devtools.ksp" }
