apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-VAR_SERVICE_NAME
  namespace: VAR_NAMESPACE_KUBERNETES
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /VAR_SERVICE_NAME/health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: apps.production
    alb.ingress.kubernetes.io/load-balancer-name: caju-alb-int-production-main
    alb.ingress.kubernetes.io/subnets: subnet-0c9baa2f6c6323edf, subnet-09f9884459c03746a, subnet-0f9d5b6fbc340717e
    alb.ingress.kubernetes.io/tags: Environment=production
spec:
  ingressClassName: alb
  rules:
    - host: "VAR_SERVICE_NAME.caju.app"
      http:
        paths:
          - path: /VAR_SERVICE_NAME
            pathType: Prefix
            backend:
              service:
                name: "svc-VAR_SERVICE_NAME-primary"
                port:
                  name: http