apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-VAR_SERVICE_NAME
  namespace: VAR_NAMESPACE_KUBERNETES
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /VAR_SERVICE_NAME/health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: apps.staging-002
    alb.ingress.kubernetes.io/load-balancer-name: staging-caju-alb-internal-002
    alb.ingress.kubernetes.io/subnets: subnet-0856782c6ea7aecf9, subnet-086226fa9684965a4, subnet-0aa74683c1bd9d3c4
    alb.ingress.kubernetes.io/tags: Environment=staging
spec:
  ingressClassName: alb
  rules:
    - host: "VAR_SERVICE_NAME-staging.caju.app"
      http:
        paths:
          - path: /VAR_SERVICE_NAME
            pathType: Prefix
            backend:
              service:
                name: "svc-VAR_SERVICE_NAME-primary"
                port:
                  name: http