services:
  mysql:
    image: mysql:8.2.0
    platform: linux/arm64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "<project-name>"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "mysql" ]
      interval: 10s
      timeout: 0.5s
      retries: 5

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql?allowPublicKeyRetrieval=true -schemas=<project-name> -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ./driven/persistence/src/main/resources/db/migration:/flyway/sql/default
      - ./.docker/database:/flyway/sql/seed
    depends_on:
      - mysql

  wiremock:
    image: wiremock/wiremock:3.3.1
    ports:
      - "9561:9561"
    volumes:
      - ./.docker/wiremock:/home/wiremock
    command: --port 9561 --local-response-templating --verbose

  zoo:
    image: confluentinc/cp-zookeeper:7.6.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: "zookeeper:22888:23888"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${pi:-127.0.0.1}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: |
        tp_person
        tp_person_dlq

      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "nc", "-z", "kafka", "19092" ]
      interval: 10s
      timeout: 0.5s
      retries: 5
    command:
      - /bin/sh
      - -c
      - |
        (echo 'Waiting for Kafka to be ready...'
        cub kafka-ready -b kafka:19092 1 30
        for topic in $$KAFKA_CREATE_TOPICS;
        do
          echo "Creating $$topic..."
          kafka-topics --create --if-not-exists --bootstrap-server kafka:19092 --partitions 1 --replication-factor 1 --topic $$topic
        done;)&
        /etc/confluent/docker/run
    depends_on:
      - zoo

  akhq:
    image: tchiotludo/akhq:0.25.1
    ports:
      - "8000:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:19092"
          topic-data:
            sort: NEWEST
    depends_on:
      - kafka
      - zoo

  localstack:
    image: localstack/localstack:3.5.0
    ports:
      - "4566:4566"
      - "8082:8080"
    environment:
      - SERVICES=s3
      - DEBUG=0
    volumes:
      - ./.docker/localstack:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock

  locust-master:
    image: locustio/locust:2.31.6
    ports:
      - "8089:8089"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - LOCUST_HOST=http://host.docker.internal:8080/<project-name>
      - LOCUST_USERS=15
      - LOCUST_SPAWN_RATE=3
      - LOCUST_RUN_TIME=60
      - LOCUST_LOCUSTFILE=/home/locust
      - LOCUST_MODE_MASTER=true
    volumes:
      - ./.docker/locust/mappings:/home/locust

  locust-worker:
    image: locustio/locust:2.31.6
    deploy:
      replicas: 3
    environment:
      - LOCUST_LOCUSTFILE=/home/locust
      - LOCUST_MODE_WORKER=true
      - LOCUST_MASTER_NODE_HOST=locust-master
    volumes:
      - ./.docker/locust/mappings:/home/locust
