[versions]
# https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies
spring-cloud = "2023.0.3"
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot
spring-boot = "3.3.4"
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin
kotlin = "2.0.21"
# https://mvnrepository.com/artifact/org.barfuin.gradle.jacocolog/org.barfuin.gradle.jacocolog.gradle.plugin
jacoco = "2.0.0"
# https://plugins.gradle.org/plugin/org.sonarqube
sonarqube = "4.4.1.3373"
# https://mvnrepository.com/artifact/com.diffplug.spotless/spotless-plugin-gradle
spotless = "6.25.0"
# https://mvnrepository.com/artifact/io.kotest/kotest-runner-junit5-jvm
kotest = "5.9.1"
# https://mvnrepository.com/artifact/io.kotest.extensions/kotest-extensions-spring
kotest-spring = "1.3.0"
# https://mvnrepository.com/artifact/io.kotest/kotest-extensions-now-jvm
kotest-now = "5.9.1"
# https://mvnrepository.com/artifact/org.instancio/instancio-junit
instancio = "5.0.2"
# https://mvnrepository.com/artifact/org.assertj/assertj-core
assertj = "3.26.3"
# https://mvnrepository.com/artifact/com.ninja-squad/springmockk
spring-mockk = "4.0.2"
# https://mvnrepository.com/artifact/net.logstash.logback/logstash-logback-encoder
logback-encoder = "8.0"
# https://mvnrepository.com/artifact/com.datadoghq/dd-trace-api
datadog = "1.41.0"
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core
kotlinx = "1.9.0"
# https://mvnrepository.com/artifact/io.projectreactor.netty/reactor-netty
reactor-netty = "1.1.23"
# https://mvnrepository.com/artifact/org.wiremock/wiremock-standalone
wiremock = "3.9.1"
# https://mvnrepository.com/artifact/org.testcontainers/testcontainers
testcontainers = "1.20.2"
# https://mvnrepository.com/artifact/software.amazon.awssdk/aws-core
aws-sdk = "2.28.24"
# https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui
spring-docs = "2.6.0"
java = "21"
[libraries]
spring-boot-cloud-dependencies = { version.ref = "spring-cloud", module = "org.springframework.cloud:spring-cloud-dependencies"}
spring-boot-dependencies = { version.ref = "spring-boot", module = "org.springframework.boot:spring-boot-dependencies"}
kotlinx-coroutines-core = { version.ref = "kotlinx", module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"}
kotlinx-coroutines-reactor = { version.ref = "kotlinx", module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor"}
kotlinx-coroutines-reactive = { version.ref = "kotlinx", module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive"}
logback-encoder = { version.ref = "logback-encoder", module = "net.logstash.logback:logstash-logback-encoder"}
dd-trace-api = { version.ref = "datadog", module = "com.datadoghq:dd-trace-api"}
springmockk = { version.ref = "spring-mockk", module = "com.ninja-squad:springmockk"}
kotest-runner-junit5-jvm = { version.ref = "kotest", module = "io.kotest:kotest-runner-junit5-jvm"}
kotest-assertions-core-jvm = { version.ref = "kotest", module = "io.kotest:kotest-assertions-core-jvm"}
kotest-property-jvm = { version.ref = "kotest", module = "io.kotest:kotest-property-jvm"}
kotest-extensions-spring = { version.ref = "kotest-spring", module = "io.kotest.extensions:kotest-extensions-spring"}
kotest-extensions-now = { version.ref = "kotest-now", module = "io.kotest:kotest-extensions-now"}
instancio-junit = { version.ref = "instancio", module = "org.instancio:instancio-junit"}
assertj-core = { version.ref = "assertj", module = "org.assertj:assertj-core"}
reactor-netty = { version.ref = "reactor-netty", module = "io.projectreactor.netty:reactor-netty"}
wiremock-standalone = { version.ref = "wiremock", module = "org.wiremock:wiremock-standalone"}
testcontainers-mysql = { version.ref = "testcontainers", module = "org.testcontainers:mysql"}
aws-s3 = { version.ref = "aws-sdk", module = "software.amazon.awssdk:s3"}
aws-sts = { version.ref = "aws-sdk", module = "software.amazon.awssdk:sts"}
aws-core = { version.ref = "aws-sdk", module = "software.amazon.awssdk:core"}
springdoc-openapi-starter-webmvc-ui = { version.ref = "spring-docs", module = "org.springdoc:springdoc-openapi-starter-webmvc-ui"}
[plugins]
spring-boot = { version.ref = "spring-boot", id = "org.springframework.boot"}
spring-cloud = { version.ref = "spring-cloud", id = "org.springframework.cloud"}
kotlin = { version.ref = "kotlin", id = "org.jetbrains.kotlin.jvm"}
kotlin-spring = { version.ref = "kotlin", id = "org.jetbrains.kotlin.plugin.spring"}
kotlin-all-open = { version.ref = "kotlin", id = "org.jetbrains.kotlin.plugin.all-open"}
kotlin-jpa = { version.ref = "kotlin", id = "org.jetbrains.kotlin.plugin.jpa"}
jacoco = { version.ref = "jacoco", id = "org.barfuin.gradle.jacocolog"}
sonarqube = { version.ref = "sonarqube", id = "org.sonarqube"}
spotless = { version.ref = "spotless", id = "com.diffplug.spotless"}

