apiVersion: apps/v1
kind: Deployment
metadata:
  name: VAR_SERVICE_NAME
spec:
  template:
    spec:
      containers:
        - name: VAR_SERVICE_NAME
          env:
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets-VAR_SERVICE_NAME
                  key: DATADOG_API_KEY
                  optional: false
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "secrets-VAR_SERVICE_NAME"
