management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: caju-slack-mode-kafka-consumer
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:29092}
    properties:
      json.fail.unknown.properties: false
      json.write.dates.iso8601: true
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 5
      fetch-min-size: 1
      properties:
        max.poll.interval.ms: 6000000
        spring.json.trusted.packages: br.com.caju
    listener:
      ack-mode: manual
  jackson:
    time-zone: UTC
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    default-leniency: true
    deserialization:
      fail-on-unknown-properties: false
