management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  sql:
    init:
      mode: always
  application:
    name: {{ cookiecutter.project_name }}-consumer
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:{{cookiecutter.project_slug.replace('-', '_')}}}
    username: ${APP_DB_USER:{{cookiecutter.project_slug.replace('-', '_')}}_user}
    password: ${APP_DB_PASSWORD:{{cookiecutter.project_slug.replace('-', '_')}}_password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 1
      transaction-isolation: TRANSACTION_READ_COMMITTED
      driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:29092}
    properties:
      json.fail.unknown.properties: false
      json.write.dates.iso8601: true
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 5
      fetch-min-size: 1
      properties:
        max.poll.interval.ms: 6000000
        spring.json.trusted.packages: br.com.caju
    listener:
      ack-mode: manual
  jackson:
    time-zone: UTC
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    default-leniency: true
    deserialization:
      fail-on-unknown-properties: false
