server:
  port: ${HTTP_PORT:8080}
  servlet:
    context-path: /{{cookiecutter.project_slug}}

springdoc:
  swagger-ui:
    path: /docs
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    syntax-highlight:
      theme: agate
    query-config-enabled: true
  api-docs:
    path: /v3/api-docs
  show-login-endpoint: false
  use-management-port: false

management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: heapdump,health

aws:
  region: ${AWS_REGION:sa-east-1}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:{{cookiecutter.project_slug}}}
    pre-sign-duration: ${AWS_S3_PRE_SIGN_DURATION:60}

spring:
  sql:
    init:
      mode: always
  application:
    name: {{ cookiecutter.project_slug }}-http-api
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:{{cookiecutter.project_slug.replace('-', '_')}}}
    username: ${APP_DB_USER:{{cookiecutter.project_slug.replace('-', '_')}}_user}
    password: ${APP_DB_PASSWORD:{{cookiecutter.project_slug.replace('-', '_')}}_password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 1
      transaction-isolation: TRANSACTION_READ_COMMITTED
      driver-class-name: org.postgresql.Driver
{% if cookiecutter.include_kafka_events == "y" %}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:29092}
    properties:
      acks: all
      enable.idempotence: true
      json.fail.unknown.properties: false
      json.write.dates.iso8601: true
      request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT_MS:20000}
      retries: 5
      retry.backoff.ms: ${KAFKA_RETRY_BACKOFF_MS:500}
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 5
      fetch-min-size: 1
      properties:
        max.poll.interval.ms: 6000000
        spring.json.trusted.packages: br.com.caju
    listener:
      async-acks: true
{% endif %}
  jackson:
    time-zone: UTC
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    default-leniency: true
    deserialization:
      fail-on-unknown-properties: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

rest-client:
  {{ cookiecutter.resource_name_lower }}:
    url:
      base: ${{ "${" }}{{cookiecutter.resource_name_constant}}_BASE_URL:http://localhost:9561{{ "}" }}
      context-path: ${{ "${" }}{{cookiecutter.resource_name_constant}}_CONTEXT_PATH:/{{cookiecutter.resource_name_lower}}{{ "}" }}
